paths:
  raw: gosales/data/raw
  staging: gosales/data/staging
  curated: gosales/data/curated
  outputs: gosales/outputs
database:
  engine: sqlite          # sqlite | duckdb | azure
  sqlite_path: gosales/gosales.db
run:
  cutoff_date: "2024-12-31"
  prediction_window_months: 6
  lookback_years: 3
etl:
  coerce_dates_tz: "UTC"
  currency: "USD"
  fail_on_contract_breach: true
  allow_unknown_columns: false
logging:
  level: INFO
  jsonl: true
labels:
  gp_min_threshold: 0.0
  denylist_skus_csv: gosales/data/lookup/label_denylist_skus.csv
features:
  windows_months: [3, 6, 12, 24]
  gp_winsor_p: 0.99
  add_missingness_flags: true
  use_eb_smoothing: true
  use_market_basket: true
  use_als_embeddings: true
  use_item2vec: false
  use_text_tags: false
modeling:
  seed: 42
  folds: 3
  models: [logreg, lgbm]
  lr_grid:
    l1_ratio: [0.0, 0.2, 0.5]
    C: [0.1, 1.0, 10.0]
  lgbm_grid:
    num_leaves: [31, 63]
    min_data_in_leaf: [50, 100]
    learning_rate: [0.05, 0.1]
    feature_fraction: [0.7, 0.9]
    bagging_fraction: [0.7, 0.9]
  calibration_methods: [platt, isotonic]
  top_k_percents: [5, 10, 20]
  capacity_percent: 10

whitespace:
  weights: [0.60, 0.20, 0.10, 0.10]   # [p_icp_pct, lift_norm, als_norm, EV_norm]; non-negative, auto-normalized
  normalize: percentile               # percentile | pooled
  eligibility:
    exclude_if_owned_ever: true
    exclude_if_recent_contact_days: 21
    exclude_if_open_deal: true
    require_region_match: true
  capacity_mode: top_percent          # top_percent | per_rep | hybrid
  accounts_per_rep: 25
  ev_cap_percentile: 0.95
  als_coverage_threshold: 0.30
  bias_division_max_share_topN: 0.6
  cooldown_days: 30
  cooldown_factor: 0.75
  # Optional challenger meta-learner over [p_icp_pct, lift_norm, als_norm, EV_norm]
  challenger_enabled: false
  challenger_model: lr
  # Emit legacy heuristic whitespace alongside Phase-4 outputs for comparison
  shadow_mode: false

validation:
  bootstrap_n: 1000
  top_k_percents: [5, 10, 20]
  capacity_grid: [5, 10, 20]
  ev_cap_percentile: 0.95
  segment_columns: [industry, industry_sub, region, territory]
  ks_threshold: 0.15
  psi_threshold: 0.25


