paths:
  raw: gosales/data/raw
  staging: gosales/data/staging
  curated: gosales/data/curated
  outputs: gosales/outputs
database:
  engine: azure
  sqlite_path: gosales/gosales.db
  strict_db: false
  source_tables:
    industry_enrichment: csv
    items_category_limited: dbo.items_category_limited
  allowed_identifiers:
  - industry_enrichment
  - dbo.items_category_limited
  curated_target: sqlite
  curated_sqlite_path: gosales/gosales_curated.db
run:
  cutoff_date: '2024-12-31'
  prediction_window_months: 6
  lookback_years: 3
  training_cutoffs: []
  training_frequency_months: 6
  training_cutoff_count: 4
etl:
  coerce_dates_tz: UTC
  currency: USD
  fail_on_contract_breach: true
  allow_unknown_columns: false
  enable_industry_fuzzy: false
  fuzzy_min_unmatched: 50
  fuzzy_skip_if_coverage_ge: 0.95
  fuzzy_max_unmatched: 20000
  fuzzy_cache_path: gosales/outputs/industry_fuzzy_matches.csv
  industry_enrichment_csv: gosales/data/database_samples/TR - Industry Enrichment.csv
  source_columns:
    customer_id: CompanyId
    order_date: Rec_Date
    division: division
    customer_name: New_Business
  dim_customer:
    sources:
    - ns
    - assets
  assets:
    emit_debug_columns: true
logging:
  level: INFO
  jsonl: true
population:
  include_prospects: false
  warm_window_months: 18
  exclude_prospects_in_features: true
  build_segments:
  - warm
  - cold
labels:
  gp_min_threshold: 0.0
  denylist_skus_csv: gosales/data/lookup/label_denylist_skus.csv
features:
  windows_months:
  - 3
  - 6
  - 12
  - 24
  gp_winsor_p: 0.99
  add_missingness_flags: true
  use_eb_smoothing: true
  use_market_basket: true
  use_als_embeddings: true
  als_weight_by_quantity: true
  als_weight_include_revenue: true
  als_weight_price_factor: 1.0
  als_weight_cap: null
  als_weight_stats_sample_rows: 100000
  als_division_scoped: true
  als_scope_by_goal: true
  als_revenue_cap_usd: null
  als_revenue_cap_by_division: {}
  als_time_decay_enabled: true
  als_time_half_life_days: 180
  als_min_scoped_interactions: 1000
  als_lookback_months: 24
  use_item2vec: false
  use_assets_als: true
  assets_als:
    max_rows: 80000
    max_cols: 200
    factors: 16
    iters: 4
    reg: 0.1
  use_text_tags: false
  use_assets: true
  expiring_guard_days: 30
  recency_floor_days: 30
  recency_decay_half_lives_days:
  - 30
  - 90
  - 180
  enable_offset_windows: true
  offset_days:
  - 60
  enable_window_deltas: true
  affinity_lag_days: 60
  pooled_encoders_enable: true
  pooled_encoders_lookback_months: 24
  pooled_alpha_industry: 50.0
  pooled_alpha_sub: 50.0
  silence_pooled_encoder_warnings: true
  segment_feature_allowlist:
    warm:
    - rfm__
    - recency
    - log_recency
    - decay
    - margin__
    - total_
    - avg_
    - tx_
    - gp_
    - xdiv__
    - diversity
    - enc__
    - is_
    - assets_
    cold:
    - assets_
    - enc__
    - is_
    - cust_cat_
    - cust_feat_
    - region
    - territory
    - industry
modeling:
  seed: 42
  folds: 3
  models:
  - lgbm
  - logreg
  n_jobs: 1
  lr_grid:
    l1_ratio:
    - 0.0
    - 0.2
    - 0.5
    C:
    - 0.1
    - 1.0
    - 10.0
  lgbm_grid:
    num_leaves:
    - 31
    - 63
    min_data_in_leaf:
    - 50
    - 100
    learning_rate:
    - 0.05
    - 0.1
    feature_fraction:
    - 0.7
    - 0.9
    bagging_fraction:
    - 0.7
    - 0.9
  calibration_methods:
  - platt
  - isotonic
  top_k_percents:
  - 5
  - 10
  - 20
  capacity_percent: 10
  shap_max_rows: 50000
  final_calibration_max_rows: 50000
  class_weight: balanced
  use_scale_pos_weight: true
  scale_pos_weight_cap: 10.0
  safe_divisions: []
  stability:
    coverage_floor: 0.0
    min_positive_rate: 0.0
    min_positive_count: 0
    penalty_lambda: 0.0
    cv_guard_max: null
    sparse_family_prefixes: []
    backbone_features: []
    backbone_prefixes: []
whitespace:
  weights:
  - 0.6
  - 0.2
  - 0.1
  - 0.1
  normalize: percentile
  eligibility:
    exclude_if_owned_ever: true
    exclude_if_recent_contact_days: 21
    exclude_if_open_deal: true
    require_region_match: true
    exclude_if_active_assets: true
    reinclude_if_assets_expired_days: 365
  capacity_mode: top_percent
  accounts_per_rep: 25
  segment_allocation:
    warm: 0.7
    cold: 0.3
    prospect: 0.0
  ev_cap_percentile: 0.95
  als_coverage_threshold: 0.3
  als_blend_weights:
  - 0.5
  - 0.5
  bias_division_max_share_topN: 0.6
  cooldown_days: 30
  cooldown_factor: 0.75
  challenger_enabled: true
  challenger_model: lr
  shadow_mode: false
  segment_columns:
  - industry
  - size_bin
  segment_min_rows: 250
validation:
  bootstrap_n: 1000
  top_k_percents:
  - 5
  - 10
  - 20
  capacity_grid:
  - 5
  - 10
  - 20
  ev_cap_percentile: 0.95
  segment_columns:
  - industry
  - industry_sub
  - region
  - territory
  ks_threshold: 0.15
  psi_threshold: 0.25
  holdout_required: true
  holdout_source: auto
  shift14_epsilon_auc: 0.01
  shift14_epsilon_lift10: 0.25
  ablation_epsilon_auc: 0.01
  ablation_epsilon_lift10: 0.25
  gauntlet_mask_tail_days: 60
  gauntlet_purge_days: 60
  gauntlet_label_buffer_days: 30
