paths:
  raw: gosales/data/raw
  staging: gosales/data/staging
  curated: gosales/data/curated
  outputs: gosales/outputs
database:
  engine: sqlite          # sqlite | duckdb | azure
  sqlite_path: gosales/gosales.db
run:
  cutoff_date: "2024-12-31"
  prediction_window_months: 6
  lookback_years: 3
etl:
  coerce_dates_tz: "UTC"
  currency: "USD"
  fail_on_contract_breach: true
  allow_unknown_columns: false
logging:
  level: INFO
  jsonl: true
labels:
  gp_min_threshold: 0.0
  denylist_skus_csv: gosales/data/lookup/label_denylist_skus.csv
features:
  windows_months: [3, 6, 12, 24]
  gp_winsor_p: 0.99
  add_missingness_flags: true
  use_eb_smoothing: true
  use_market_basket: true
  use_als_embeddings: false
  use_item2vec: false
  use_text_tags: false


