channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=24.3.1
- pip:
  - mlflow==3.1.4
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - graphviz==0.21
  - lightgbm==4.6.0
  - matplotlib==3.10.5
  - numpy==2.2.6
  - pandas==2.2.3
  - pyarrow==20.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
