channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=25.0.1
- pip:
  - mlflow==3.1.4
  - cffi==1.17.1
  - cloudpickle==3.1.1
  - graphviz==0.21
  - lightgbm==4.6.0
  - matplotlib==3.10.0
  - numpy==2.2.2
  - pandas==2.2.3
  - pyarrow==20.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.0
name: mlflow-env
