[theme]
primaryColor = "#BAD532"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F8FA"
textColor = "#222222"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false
